modLoader = "javafml" #mandatory
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "groovy_test"
version = "${file.jarVersion}"
displayName = "GroovyTest"
description = '''

'''
[[dependencies.groovy_test]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.groovy_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
